### ISSUE TITLE
关于项目分层架构的问题

### ISSUE THREAD

**Issue by chenmudu** [3kuai/hanboDB#3]
想基于您这个项目进行学习和设计，但是有关项目启动如何测试还是没有搞懂。请问可以向您要一份关于代码结构和如何启动如何测试的说明书吗。如果有真将感激不尽。

**Comment by alansfa** [comment]
maven编译，springboot启动不是难事吧😄

**Comment by chenmudu** [comment]
😭，启动当然没问题。有很多疑惑。对您这个项目特别感兴趣。所以能不能给我一份手册。大概讲讲如何测试如何看懂您的设计的文档吗。如果有真的感激不尽。

**Comment by chenmudu** [comment]
您可以给我您的私人联系方式吗。比如WeChat或者QQ。就是想要一份关于本项目的说明书。

lucas <notifications@github.com> 于2019年7月16日周二 下午5:06写道：

**Comment by alansfa** [comment]
@chenmudu  你是做毕业设计嘛

**Comment by chenmudu** [comment]
用于自己学习的。您能给予我一份文档吗。如果有。不胜感激。

lucas <notifications@github.com> 于2019年7月29日周一 下午8:25写道：

**Comment by alansfa** [comment]
@chenmudu  https://my.oschina.net/u/4177567/blog/3082682

**Comment by chenmudu** [comment]
好的。谢谢。

lucas <notifications@github.com> 于2019年8月4日周日 上午10:28写道：
