### ISSUE TITLE
password  Support and  optimization RedisCommandProcessorImpl  code long

### ISSUE THREAD

**Issue by a610569731** [3kuai/hanboDB#4]

**Comment by alansfa** [comment]
@a610569731 great.

**Comment by a610569731** [comment]
value bytes long java.net.SocketTimeoutException: Read timed out 
for(int i=0;i<100;i++) {
		 	System.out.println("i "+i);
			jedis.hset("user:1001","kk:"+i,"testtesttesttesttesttesttesttesttesttesttesttest")；
}

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:153)

**Comment by lmx1989219** [comment]
你数据量有多大？



---Original---

**Comment by lmx1989219** [comment]
欢迎提交pr，一起来完善




---Original---
From: "lucas"<285980382@qq.com&gt;
Date: Mon, Oct 7, 2019 21:10 PM
To: "3kuai/hanboDB"<reply@reply.github.com&gt;;
Subject: Re: [3kuai/hanboDB] password  Support and  optimization RedisCommandProcessorImpl  code long (#4)


你数据量有多大？



---Original---

**Comment by lmx1989219** [comment]
welcome to join my team，submit PR&nbsp; or&nbsp; suggestion，we will do it well



---Original---

**Comment by a610569731** [comment]
不大啊 https://juejin.im/post/5aaf1e0af265da2381556c0e 直接抄这个解析就没问题

**Comment by lmx1989219** [comment]
> 

已经解决了，是请求指令解码时粘包未处理干净的问题

**Comment by alansfa** [comment]
> value bytes long java.net.SocketTimeoutException: Read timed out for(int i=0;i<100;i++) { System.out.println("i "+i); jedis.hset("user:1001","kk:"+i,"testtesttesttesttesttesttesttesttesttesttesttest")； }
> 
> redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202) at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40) at redis.clients.jedis.Protocol.process(Protocol.java:153)

已经解决了，是请求指令解码时粘包未处理干净的问题 @a610569731
